apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}-service
  labels:
    app: {{ include "helloworld.name" . }}
    chart: {{ include "helloworld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "helloworld.name" . }}
